# Generated by Django 3.2 on 2021-05-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0002_remove_technicien_idadmin'),
        ('client', '0005_rename_id_client_offre_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.offre')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicien.technicien')),
            ],
            options={
                'db_table': 'postuler',
            },
        ),
    ]
