# Generated by Django 3.2 on 2021-06-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0002_remove_technicien_idadmin'),
        ('client', '0006_postuler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicien.technicien')),
            ],
            options={
                'ordering': ('date_sent',),
            },
        ),
    ]
