# Generated by Django 3.2 on 2021-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('mdp', models.CharField(max_length=30)),
            ],
        ),
    ]
