# Generated by Django 3.2 on 2021-05-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='idAdmin',
        ),
    ]
